### ISSUE TITLE
[Bug] Automatic creation of ExtensionBase file replaces too many classnames

### ISSUE THREAD

**Issue by roland-d** [pjdevries/plg_system_classextender#9]
When the class extender automatically creates the `ExtensionBase` file, in some cases it can change too many strings. An example is the file `libraries/src/Table/Content.php`.

The JSON entry is:
```
[
  {
    "class": "Content",
    "file": "libraries/src/Table/Content.php"
  }
]
```

The ExtensionBase file is created correct but then the classname is replaced from `Content` to `ContentExtensionBase`. However further in the file, this line is also changed:
```php
$table = Table::getInstance('Content', 'JTable', array('dbo' => $this->getDbo()));
```
Now this has become:
```
$table = Table::getInstance('ContentExtensionBase', 'JTable', array('dbo' => $this->getDbo()));
```
Which results in a fatal error because `$table` is `null`.

Replacing the classname should be a bit more strict.

**Comment by pjdevries** [comment]
@roland-d Bij mij gebeurt dit niet. Met welke versie heb je dit probleem?

Zou kunnen dat ik dit inmiddels heb opgelost, maar nog niet gereleased :D

**Comment by roland-d** [comment]
@pjdevries Je had gevraagd of ik het een en ander wil testen maar ik zie geen nieuwe commits. Moet je nog pushen?

**Comment by pjdevries** [comment]
@roland-d Blijkbaar :) Nu wel, als het goed is.

**Comment by roland-d** [comment]
@pjdevries Het gaat goed nu. Tijd voor een nieuwe release?

**Comment by pjdevries** [comment]
@roland-d Nieuwe release staat er.
